import {Item} from './item';

export const  mockItems:Item[] = [
        {
            type:'วัสดุ',
            group:'วัสดุโครงการ',
            list:'Smart Watch',
            name:'Fitbit Charge2',
            model:'Charge2',
            brand:'Fitbit',
            price: 0,
            balance: 120,
            unit:'กล่อง',
            buy_place: 'บันเลือง ซินอินเตอร์ จำกัด',
            keep_place: 'ห้องพักอาจารย์',
            attendant: 'กิตติยา',
            note: 'Update 28/01/62'
        },
        {
            type:'วัสดุ',
            group:'วัสดุโครงการ',
            list:'Smart Watch',
            name:'Fitbit Versa',
            model:'Versa',
            brand:'Fitbit',
            price: 0,
            balance: 800,
            unit:'กล่อง',
            buy_place: 'บันเลือง ซินอินเตอร์ จำกัด',
            keep_place: 'ห้องพักอาจารย์',
            attendant: 'กิตติยา',
        },
        {
            type:'ครุภัณฑ์',
            group:'ครุภัณฑ์โครงการ',
            list:'LEGO',
            name:'LEGO EV3',
            model:'EV3',
            brand:'MINDSTORMS',
            price: 0,
            balance: 25,
            unit:'ชุด',
            buy_place: '',
            keep_place: 'WSN',
            attendant: 'วรโชติ',
        },
        {
            type:'วัสดุ',
            group:'วัสดุสำนักงาน',
            list:'กระดาษ',
            name:'กระดาษ DoubleA A4',
            model:'A4',
            brand:'Double A',
            price: 0,
            balance: 5,
            unit:'รีม',
            buy_place: 'Officemate',
            keep_place: 'ห้องพักอาจารย์',
            attendant: 'อมรรัตน์',
        },
    ]
